### ISSUE TITLE
Get this thing to work sprint

### ISSUE THREAD

**Issue by axic** [ewasm/evm2wasm#238]
- [ ] remove non-folded instructions [#213]
- [ ] figure out how to do VM tests with hera
- [ ] make the c++ work with hera (to speed up tests)
- [ ] change `generateInterface.js` to support C++ header [#237]
- [ ] change the starting stack pointer from -32 to 0
- [ ] update to byzantium [#137, #163, #164]
- [ ] update to latest EEI [#184]
